# Generated by Django 4.0.3 on 2022-12-22 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interfaz_principal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacto',
            name='telefono',
            field=models.CharField(max_length=300),
        ),
    ]
